cpv_list:
  - 72221000  # Beratung zu Business-Analyse
  - 72224000  # Projektmanagement-Beratung
  - 72316000  # Datenanalyse-Dienste
  - 72262000  # Software-Entwicklung
  - 72514000  # IT-Betriebsleistungen
  - 79417000  # Beratung zu Informationssicherheit
regions: [DE9, DE6, DEE, DE7, DEG]          # NUTS: NI, HH, ST, HE, TH
branch_keywords:
  - Automotive
  - Mobilität
  - Energie
  - Verwaltung
  - öffentliche Ausschreibungen
  - Rundfunk- und Medienanstalten
  - Versicherungen
min_budget: 50000
period: "letzte 30 Tage"
top_n: 20
json_limit: 150
min_hits: 10
