cpv_list:
  - 72221000  # Beratung zu Business-Analyse
  - 72224000  # Projektmanagement-Beratung
  - 72316000  # Datenanalyse-Dienste
  - 72262000  # Software-Entwicklung
  - 72514000  # IT-Betriebsleistungen
  - 79417000  # Beratung zu Informationssicherheit
  - 72000000  # Dienstleistungen im Bereich Informationstechnologie
  - 72200000  # Software-Programmierung und -Beratung
  - 72260000  # Software-Entwicklung
  - 72400000  # IT-Dienstleistungen: Beratung, Software-Entwicklung, Internet und Support
  - 72600000  # Datenverarbeitung und IT-Sicherheitsberatung
  - 72700000  # Dienstleistungen im Bereich Datenverarbeitung
  - 48800000  # Softwarepakete und Informationssysteme
  - 30200000  # Computergeräte und Zubehör
  - 38420000  # Künstliche Intelligenz und verwandte Dienstleistungen
regions: [DE9, DE6, DEE, DE7, DEG]          # NUTS: NI, HH, ST, HE, TH
branch_keywords:
  - Automotive
  - Mobilität
  - Energie
  - Verwaltung
  - öffentliche Ausschreibungen
  - Rundfunk- und Medienanstalten
  - Versicherungen
min_budget: 50000
period: "letzte 30 Tage"
top_n: 20
json_limit: 150
min_hits: 10
